### ISSUE TITLE
Internal review

### ISSUE THREAD

**Issue by Robinlovelace** [ATFutures/calendar#14]
@mpadge are you up for a first bash at this?

Could be a good chance to test this new `pkgreview` package: https://ropenscilabs.github.io/pkgreviewr/index.html

**Comment by mpadge** [comment]
Yep, love to. Thanks!

**Comment by Robinlovelace** [comment]
Great. There are still a few things I want to sort out before taking-up your time. Can I ping you when I think it's ready?
