### ISSUE TITLE
Interaction with ical on CRAN

### ISSUE THREAD

**Issue by Robinlovelace** [ATFutures/calendar#24]
https://cran.r-project.org/web/packages/ical/index.html

How should they fit together? Does the newer package supercede this one? Perhaps it could become an **icaltools** package for creating and modifying ical files...

**Comment by layik** [comment]
With no disrespect to that `ical`, I think this `ical` is superior. It could easily ignore it. We saw no reason of "parse"ing .ical to resort to `js` code. Should I do a benchmark exercise to justify my attack? 

PS: CRAN allows simple packages into C`R`AN.

**Comment by layik** [comment]
The name is taken so would have to call it something else, the other option is to speak to the developers and merge, I think the latter is much more "open source"y and commonsense of going about it.

**Comment by layik** [comment]
Running a bechmark function on "parse"by both packages. Will report here.

**Comment by layik** [comment]
```
benchmark(ical = ical::ical_parse("inst/extdata/england-and-wales.ics"), icalr=icalr::ic_read("inst/extdata/england-and-wales.ics"))
   test replications elapsed relative user.self sys.self user.child sys.child
1  ical          100   0.415    1.000     0.413    0.008          0         0
2 icalr          100   0.667    1.607     0.667    0.000          0         0
```
ical is the CRAN
icalr is this package.
Amazing, how JS is faster than R, sorry. 
cc @Robinlovelace

**Comment by Robinlovelace** [comment]
Heads-up @petermeissner

**Comment by petermeissner** [comment]
Hey, this seams like an unfortunate parallel development ... Maybe we can have a chat sometime this week to discuss mission, scope, motivation, overlap and possible room for collaboration - if this is something you would consider.

**Comment by Robinlovelace** [comment]
Sounds good but will have to be next week for me - a busy one.

Not necessarily unfortunate: sure there are synergies.

Thanks @layik for suggestion and Peter for collaborating - I think these pkgs can be mutually beneficial.

**Comment by petermeissner** [comment]
Sounds good, are you folks on Twitter to talk about when to talk via direct
message ... or give me a message at: retep dot meissner at gmail dot com. I
am quite flexible at the moment anything between 8 and 22 o'clock UTC
should be possible.

Am Mo., 10. Dez. 2018 um 17:04 Uhr schrieb Robin <notifications@github.com>:

**Comment by layik** [comment]
Hi @petermeissner. Got a lunch today with @Robinlovelace and will get back to you with a date/time next week.

**Comment by Robinlovelace** [comment]
Here's a comparison of features, to be updated:

``` r
features = read.csv(text = 'Feature,atfutures/ical,petermeissner/ical
Read ical file,yes,yes
Read data frame,"yes, in progress",yes
class defintion,"yes, in progress",?
write ical file,yes,?
create event,"yes, in progress",?
create calendar,yes,?')
knitr::kable(features)
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;">Feature</th>
<th style="text-align: left;">atfutures.ical</th>
<th style="text-align: left;">petermeissner.ical</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Read ical file</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Read data frame</td>
<td style="text-align: left;">yes, in progress</td>
<td style="text-align: left;">yes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">class defintion</td>
<td style="text-align: left;">yes, in progress</td>
<td style="text-align: left;">?</td>
</tr>
<tr class="even">
<td style="text-align: left;">write ical file</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">create event</td>
<td style="text-align: left;">yes, in progress</td>
<td style="text-align: left;">?</td>
</tr>
<tr class="even">
<td style="text-align: left;">create calendar</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">?</td>
</tr>
</tbody>
</table>

<sup>Created on 2018-12-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by petermeissner** [comment]
🤣

**Comment by petermeissner** [comment]
For me doing statistics on calender data is the most my must-have feature from petermeissner.ical while the class definition is most interesting from atfutures.ical.

I can imagine building on / using a proper class and filling in some gaps and adding features.

**Comment by Robinlovelace** [comment]
calendar is now on CRAN. Any ideas of how they should work together? It would be interesting to see how your package could be used the data frames that fit into the `ical` class defined in this package. Closing for now in any case.

**Comment by petermeissner** [comment]
I will have a look at the package, what it does, how it works - it might not happen within the next days though :-)
