### ISSUE TITLE
cannot create all day event

### ISSUE THREAD

**Issue by rodrigoesborges** [ATFutures/calendar#35]
I tried to create all day event, which , as per [this info]( https://stackoverflow.com/questions/1716237/single-day-all-day-appointments-in-ics-files) , for example, should have DTSTART and DTEND values as VALUE=DATE:YYYYmmdd

I couldn't generate the events  with proper values for DTSTART and END

I tried also to modify by hand the results, before writing to ics. But then write.ics() failed

**Comment by layik** [comment]
Hi @rodrigoesborges 
``` r
library(calendar)
s <- lubridate::ymd_h("2019-05-07 00")
ic <- ic_event(start_time = s, end_time = 0)
class(c)
#> [1] "function"
if(is(ic, "ical")) {
  ic_write(ic, "github.ics")
  readLines("github.ics")
}
#>  [1] "BEGIN:VCALENDAR"                              
#>  [2] "PRODID:-//ATFutures/ical //EN"                
#>  [3] "VERSION:2.0"                                  
#>  [4] "CALSCALE:GREGORIAN"                           
#>  [5] "METHOD:PUBLISH"                               
#>  [6] "BEGIN:VEVENT"                                 
#>  [7] "UID:ical-3ce23907-9f22-4d90-abed-f5662508f842"
#>  [8] "DTSTART:20190507T000000"                      
#>  [9] "DTEND:20190507T000000"                        
#> [10] "SUMMARY:ical event"                           
#> [11] "END:VEVENT"                                   
#> [12] "END:VCALENDAR"
```

<sup>Created on 2019-05-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Am I missing something? Did you miss some date syntax? Let us know.

**Comment by Robinlovelace** [comment]
Any update on this @rodrigoesborges? There is some work to be done on this package for sure so any input welcome.

**Comment by rodrigoesborges** [comment]
Sorry for the late response, and for opening the issue. I had probably some error on my previous handling of date formats. @layik code adapted to my tests worked flawlessly.

**Comment by Robinlovelace** [comment]
No problem, thanks for follow-up.
