### ISSUE TITLE
set `COLOR` property

### ISSUE THREAD

**Issue by shamindras** [ATFutures/calendar#46]
Thank you for creating this cool package! I'm planning to use this in the near future.

I was wondering if this package enables one to set the [`COLOR` property](https://datatracker.ietf.org/doc/html/rfc7986#section-5.9) for `ics` files? I could not locate this (relatively new) color field from the [examples](https://atfutures.github.io/calendar/articles/ical-creating-calendars.html). 

Just wanted to check in case I had missed it in the documentation. If not, are there any possible workarounds to enable this using this package?

**Comment by mpadge** [comment]
Ping @Robinlovelace

**Comment by layik** [comment]
Hi @shamindras & hello @mpadge!

I doubt we were thinking about such a specific property (just learned that ics allows this) when developed the package, my thinking is that we were processing the properties not handle specific props. 

So, from the docs for [`ic_event`](https://atfutures.github.io/calendar/reference/ic_event.html), I can imagine you could use color value too:
```r
ic_event(
 ...
  format = "%Y-%m-%d %H:%M",
  ...
  color="green" 
)
```

HTH

**Comment by shamindras** [comment]
Thank you @layik for your helpful suggestion in regards to applying the `COLOR` property. I will try this out accordingly soon.

If I have any follow up queries, I'll post back here.

**Comment by layik** [comment]
Please close the ticket when you are happy or even better feel free to send a PR with any possible issue re COLOR or any other prop.

**Comment by Robinlovelace** [comment]
Great stuff guys, sorry I'm late to the party. I think that fixes it, many thanks Layik, closing for now but feel free to re-open or ask any questions @shamindras.
